---
- &1 !ruby/object:Owner
  name: A
  last_name: a
  gender: male
  contact: !ruby/object:Contact
    phone: ''
    email: a@a.com
  my_teams:
  - !ruby/object:Team
    name: Ultras
    owner: *1
    establishment: 2016-10-18
    coaches: []
  - !ruby/object:Team
    name: superDuper
    owner: *1
    establishment: 2016-10-18
    coaches:
    - !ruby/object:Coach
      name: C
      last_name: c
      gender: male
      level: assistant
  - !ruby/object:Team
    name: Rasa
    owner: *1
    establishment: 2016-10-18
    coaches: []
  - !ruby/object:Team
    name: Silute
    owner: *1
    establishment: 2016-10-18
    coaches: []
  - !ruby/object:Team
    name: Bala
    owner: *1
    establishment: 2016-10-19
    coaches: []
