require 'simplecov'
SimpleCov.start
require 'rspec'
require 'date'
require 'yaml'
require './entities/owner.rb'
require './entities/team.rb'
require './entities/coach.rb'
require './entities/contact.rb'
require './repo/owner_repo.rb'